# Generated by Django 6.0.1 on 2026-01-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
