# Generated by Django 6.0.1 on 2026-01-20 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_confession_category_delete_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite_confessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confession',
            name='comments',
            field=models.ManyToManyField(blank=True, to='core.comment'),
        ),
    ]
