# Generated by Django 6.0.1 on 2026-01-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_0007_confession_comments_able_0008_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
