# Generated by Codex on 2026-01-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tag_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
